version: 1
profiles:
  expert-juridique:
    keywords_any:
      - "droit"
      - "juridique"
      - "contrat"
      - "harcèlement"
      - "prud'hommes"
      - "déconnexion"    # aspects légaux
      - "obligation légale"
      - "temps de travail"
    keywords_not:
      - "respiration"
      - "étirements"
  expert-qvt:
    keywords_any:
      - "organisation"
      - "charge"
      - "RPS"
      - "stress au travail"
      - "prévention"
      - "micro-pause"
      - "ergonomie"
      - "ISO 45003"
      - "management"
  prof-de-yoga:
    keywords_any:
      - "respiration"
      - "cohérence cardiaque"
      - "étirements"
      - "relaxation"
      - "méditation"
      - "sommeil"
      - "insomnie"
  psy-coach:
    keywords_any:
      - "anxiété"
      - "ruminations"
      - "motivation"
      - "émotions"
      - "crise de panique"
      - "burn-out"
      - "coping"

weights:
  rule_keywords: 1.0
  user_signals: 0.8
  zero_shot:    1.2   # similarité sémantique (embeddings) si dispo

user_signal_tags:
  # tags qu’on déduit des check-ins (déjà utilisés pour les recos)
  charge:      ["charge","RPS","organisation"]
  deconnexion: ["déconnexion","temps de travail"]
  ergonomie:   ["ergonomie","pénibilité"]
  sommeil:     ["sommeil","relaxation"]
