version: 1
items:
  - url: "https://www.anact.fr/qualite-de-vie-et-des-conditions-de-travail-qvct"
    profile: "expert-qvt"
    tags: ["QVCT","organisation","prévention"]
  - url: "https://www.inrs.fr/risques/psychosociaux/ce-qu-il-faut-retenir.html"
    profile: "expert-qvt"
    tags: ["RPS","prévention","INRS"]
  - url: "https://www.inrs.fr/publications/editions/ed-6403.html"
    profile: "expert-qvt"
    tags: ["RPS","outil d'évaluation","INRS"]
  - url: "https://www.iso.org/standard/64283.html"
    profile: "expert-qvt"
    tags: ["ISO 45003","management","santé psy"]
  - url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033033747"
    profile: "expert-juridique"
    tags: ["droit à la déconnexion","temps de travail","FR"]
  - url: "https://www.cnil.fr/fr/videoprotection-et-travail"
    profile: "expert-juridique"
    tags: ["RGPD","surveillance","travail"]
  - url: "https://travail-emploi.gouv.fr/droit-du-travail/harcelement-et-violences-sexuelles-au-travail/article/le-harcelement-moral-au-travail"
    profile: "expert-juridique"
    tags: ["harcèlement moral","prévention","procédures"]
  - url: "https://www.service-public.fr/particuliers/vosdroits/F1916"
    profile: "expert-juridique"
    tags: ["durée du travail","repos","jours fériés"]
  - url: "https://www.who-5.org/"
    profile: "psy-coach"
    tags: ["WHO-5","bien-être","questionnaire"]
  - url: "https://www.allianceyoga.fr/"
    profile: "prof-de-yoga"
    tags: ["yoga","pédagogie","pranayama"]
