name: Check Secrets

on:
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secrets exist (without printing them)
        env:
          HAVE_DB: ${{ secrets.DATABASE_URL != '' }}
          HAVE_OAI: ${{ secrets.OPENAI_API_KEY != '' }}
          HAVE_MIS: ${{ secrets.MISTRAL_API_KEY != '' }}
        run: |
          echo "DATABASE_URL present? $HAVE_DB"
          echo "OPENAI_API_KEY present? $HAVE_OAI"
          echo "MISTRAL_API_KEY present? $HAVE_MIS"
          if [ "$HAVE_DB" != "true" ] || [ "$HAVE_OAI" != "true" ] || [ "$HAVE_MIS" != "true" ]; then
            echo "❌ Missing at least one secret."; exit 1;
          fi
          echo "✅ All secrets detected."
