name: Ingest RAG docs (OpenAI & Mistral)

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'ai-service/docs/**'
      - 'ai-service/ingest.py'

jobs:
  ingest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider: [openai, mistral]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List docs
        run: |
          ls -la
          ls -la ai-service || true
          ls -la ai-service/docs || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-service/requirements.txt

      - name: Sanity check imports
        run: |
          python - << 'PY'
          import sys
          import yaml
          print("PyYAML OK")
          try:
              import openai
              print("openai OK")
          except Exception as e:
              print("openai import failed:", e)
          try:
              import mistralai
              print("mistralai OK")
          except Exception as e:
              print("mistralai import failed:", e)
          PY

      - name: Run ingestion (${{ matrix.provider }})
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROVIDER: ${{ matrix.provider }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: python ai-service/ingest.py
